name: work-1
on:
  push:
    paths:
      - '.github/workflows/**'
      - 'index.html'
      - 'Dockerfile'
    branches:
      - main

jobs:
  buildImageAndPush:
    name: 도커 이미지 빌드와 푸시
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Buildx 설치
        uses: docker/setup-buildx-action@v2

      - name: 레지스트리 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 빌드 앤 푸시
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/deploy:latest
